io-services:
  reader:
    class: org.jlab.clas.std.services.convertors.HipoToHipoReader
    name: HipoToHipoReader
  writer:
    class: org.jlab.clas.std.services.convertors.HipoToHipoWriter
    name: HipoToHipoWriter
services:
  - class: org.jlab.clas.swimtools.MagFieldsEngine
    name: MAGFIELDS
  - class: org.jlab.rec.ft.cal.FTCALEngine
    name: FTCAL
  - class: org.jlab.rec.ft.hodo.FTHODOEngine
    name: FTHODO
  - class: org.jlab.rec.ft.FTEBEngine
    name: FTEB
  - class: org.jlab.service.dc.DCHBEngine
    name: DCHB
  - class: org.jlab.service.ftof.FTOFHBEngine
    name: FTOFHB
  - class: org.jlab.service.ec.ECEngine
    name: EC
  - class: org.jlab.rec.cvt.services.CVTReconstruction
    name: CVT
  - class: org.jlab.service.ctof.CTOFEngine
    name: CTOF
  - class: org.jlab.service.cnd.CNDCalibrationEngine
    name: CND
  - class: org.jlab.service.band.BANDEngine
    name: BAND
  - class: org.jlab.service.htcc.HTCCReconstructionService
    name: HTCC
  - class: org.jlab.service.ltcc.LTCCEngine
    name: LTCC
  - class: org.jlab.service.eb.EBHBEngine
    name: EBHB
  - class: org.jlab.service.dc.DCTBEngine
    name: DCTB
  - class: org.jlab.service.ftof.FTOFTBEngine
    name: FTOFTB
  - class: org.jlab.service.eb.EBTBEngine
    name: EBTB
  - class: org.jlab.rec.rich.RICHEBEngine
    name: RICH
configuration:
  io-services:
    writer:
      compression: 2
  services:
    MAGFIELDS:
      magfieldSolenoidMap: Symm_solenoid_r601_phi1_z1201_13June2018.dat
      magfieldTorusMap: Symm_torus_r2501_phi16_z251_24Apr2018.dat
      variation: rga_spring2018_mc
    CND:
      variation: rga_spring2018_mc
    CTOF:
      variation: rga_spring2018_mc
    CVT:
      variation: rga_spring2018_mc
    DCHB:
      variation: rga_spring2018_mc
      dcGeometryVariation: rga_spring2018_mc
      dcT2DFunc: "Polynomial"
    DCTB:
      variation: rga_spring2018_mc
      dcGeometryVariation: rga_spring2018_mc
    EC:
      variation: rga_spring2018_mc
    FTOFHB:
      variation: rga_spring2018_mc
    FTOFTB:
      variation: rga_spring2018_mc
    EBHB:
      variation: rga_spring2018_mc
    EBTB:
      variation: rga_spring2018_mc
      
mime-types:
  - binary/data-hipo
